# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ner.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tner.proto\"\x1a\n\nNERRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x0bNERResponse\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.Entity\"%\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t23\n\x03Ner\x12,\n\x0f\x45xtractEntities\x12\x0b.NERRequest\x1a\x0c.NERResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NERREQUEST']._serialized_start=13
  _globals['_NERREQUEST']._serialized_end=39
  _globals['_NERRESPONSE']._serialized_start=41
  _globals['_NERRESPONSE']._serialized_end=81
  _globals['_ENTITY']._serialized_start=83
  _globals['_ENTITY']._serialized_end=120
  _globals['_NER']._serialized_start=122
  _globals['_NER']._serialized_end=173
# @@protoc_insertion_point(module_scope)
